[build]
builder = "DOCKERFILE"
dockerfilePath = "khawarizmi-backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckGracePeriod = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
