import type { MethodologyVerbSlug } from "@/lib/methodology-documents"

export type MethodologyChapterLink = {
  slug: string
  domainNumero: number
  domainAr: string
  domainFr: string
  unitNumero: number
  unitAr: string
  unitFr: string
  chapterNumero: number
  chapterAr: string
  chapterFr: string
  chapterType?: string
  chapterImportance: "critique" | "haute" | "moyenne"
  scenarioId: string
  focusAr: string
  recommendedVerbs: MethodologyVerbSlug[]
}

export const methodologyChapterLinks: MethodologyChapterLink[] = [
  {
    slug: "d1-u1-c1-rappel-des-acquis",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 1,
    unitAr: "تركيب البروتين",
    unitFr: "Synthese des proteines",
    chapterNumero: 1,
    chapterAr: "تذكير بالمكتسبات",
    chapterFr: "Rappel des acquis",
    chapterType: "rappel",
    chapterImportance: "moyenne",
    scenarioId: "gene-expression-protein-disorder-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استرجاع المكتسبات الأساسية ثم توظيفها داخل وثائق وحدة تركيب البروتين.",
    recommendedVerbs: ["analyse", "justify", "scientific-text"],
  },
  {
    slug: "d1-u1-c2-siege-de-la-synthese-des-proteines",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 1,
    unitAr: "تركيب البروتين",
    unitFr: "Synthese des proteines",
    chapterNumero: 2,
    chapterAr: "مقر تركيب البروتين",
    chapterFr: "Siege de la synthese des proteines",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "gene-expression-protein-disorder-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول مقر تركيب البروتين داخل وحدة تركيب البروتين.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u1-c3-transcription-de-linformation-genetique-au-niveau-de-ladn",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 1,
    unitAr: "تركيب البروتين",
    unitFr: "Synthese des proteines",
    chapterNumero: 3,
    chapterAr: "استنساخ المعلومات الوراثية الموجودة على مستوى ADN",
    chapterFr: "Transcription de l'information genetique au niveau de l'ADN",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "gene-expression-protein-disorder-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل استنساخ المعلومات الوراثية الموجودة على مستوى ADN وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u1-c4-la-traduction",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 1,
    unitAr: "تركيب البروتين",
    unitFr: "Synthese des proteines",
    chapterNumero: 4,
    chapterAr: "الترجمة",
    chapterFr: "La traduction",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "gene-expression-protein-disorder-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل الترجمة وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u1-c5-les-etapes-de-la-traduction",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 1,
    unitAr: "تركيب البروتين",
    unitFr: "Synthese des proteines",
    chapterNumero: 5,
    chapterAr: "مراحل الترجمة",
    chapterFr: "Les etapes de la traduction",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "gene-expression-protein-disorder-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل مراحل الترجمة وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u2-c1-representation-de-la-structure-tridimensionnelle-de-la-proteine",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 2,
    unitAr: "العلاقة بين بنية ووظيفة البروتين",
    unitFr: "Relation entre structure et fonction des proteines",
    chapterNumero: 1,
    chapterAr: "تمثيل البنية الفراغية للبروتين",
    chapterFr: "Representation de la structure tridimensionnelle de la proteine",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "protein-structure-function-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول تمثيل البنية الفراغية للبروتين داخل وحدة العلاقة بين بنية ووظيفة البروتين.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u2-c2-niveaux-de-la-structure-spatiale-des-proteines",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 2,
    unitAr: "العلاقة بين بنية ووظيفة البروتين",
    unitFr: "Relation entre structure et fonction des proteines",
    chapterNumero: 2,
    chapterAr: "مستويات البنية الفراغية للبروتينات",
    chapterFr: "Niveaux de la structure spatiale des proteines",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "protein-structure-function-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول مستويات البنية الفراغية للبروتينات داخل وحدة العلاقة بين بنية ووظيفة البروتين.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u2-c3-relation-entre-structure-et-fonction-de-la-proteine",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 2,
    unitAr: "العلاقة بين بنية ووظيفة البروتين",
    unitFr: "Relation entre structure et fonction des proteines",
    chapterNumero: 3,
    chapterAr: "العلاقة بين بنية ووظيفة البروتين",
    chapterFr: "Relation entre structure et fonction de la proteine",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "protein-structure-function-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول العلاقة بين بنية ووظيفة البروتين داخل وحدة العلاقة بين بنية ووظيفة البروتين.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u3-c1-notion-denzyme-et-son-importance",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 3,
    unitAr: "النشاط الإنزيمي للبروتينات",
    unitFr: "L'activite enzymatique des proteines",
    chapterNumero: 1,
    chapterAr: "مفهوم الإنزيم وأهميته",
    chapterFr: "Notion d'enzyme et son importance",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "enzyme-activity-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول مفهوم الإنزيم وأهميته داخل وحدة النشاط الإنزيمي للبروتينات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u3-c2-lactivite-enzymatique-et-sa-relation-avec-la-structure-de-lenzyme",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 3,
    unitAr: "النشاط الإنزيمي للبروتينات",
    unitFr: "L'activite enzymatique des proteines",
    chapterNumero: 2,
    chapterAr: "النشاط الإنزيمي وعلاقته ببنية الإنزيم",
    chapterFr: "L'activite enzymatique et sa relation avec la structure de l'enzyme",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "enzyme-activity-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول النشاط الإنزيمي وعلاقته ببنية الإنزيم داخل وحدة النشاط الإنزيمي للبروتينات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u3-c3-etude-de-linfluence-du-ph-du-milieu-sur-lactivite-enzymatique",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 3,
    unitAr: "النشاط الإنزيمي للبروتينات",
    unitFr: "L'activite enzymatique des proteines",
    chapterNumero: 3,
    chapterAr: "دراسة تأثير تغير درجة pH الوسط على نشاط الإنزيم",
    chapterFr: "Etude de l'influence du pH du milieu sur l'activite enzymatique",
    chapterType: "experience",
    chapterImportance: "haute",
    scenarioId: "enzyme-activity-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استغلال المنحنيات أو التجارب المتعلقة بـ دراسة تأثير تغير درجة pH الوسط على نشاط الإنزيم بدقة عددية ومنهجية.",
    recommendedVerbs: ["analyse", "interpret", "justify", "relationship"],
  },
  {
    slug: "d1-u3-c4-etude-de-linfluence-de-la-temperature-sur-lactivite-enzymatique",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 3,
    unitAr: "النشاط الإنزيمي للبروتينات",
    unitFr: "L'activite enzymatique des proteines",
    chapterNumero: 4,
    chapterAr: "دراسة تأثير تغيرات درجة الحرارة على نشاط الإنزيم",
    chapterFr: "Etude de l'influence de la temperature sur l'activite enzymatique",
    chapterType: "experience",
    chapterImportance: "haute",
    scenarioId: "enzyme-activity-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استغلال المنحنيات أو التجارب المتعلقة بـ دراسة تأثير تغيرات درجة الحرارة على نشاط الإنزيم بدقة عددية ومنهجية.",
    recommendedVerbs: ["analyse", "interpret", "justify", "relationship"],
  },
  {
    slug: "d1-u4-c1-rappel-des-acquis",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 1,
    chapterAr: "تذكير بالمكتسبات",
    chapterFr: "Rappel des acquis",
    chapterType: "rappel",
    chapterImportance: "moyenne",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استرجاع المكتسبات الأساسية ثم توظيفها داخل وثائق وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "justify", "scientific-text"],
  },
  {
    slug: "d1-u4-c2-le-soi-et-le-non-soi",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 2,
    chapterAr: "الذات واللاذات",
    chapterFr: "Le soi et le non-soi",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الذات واللاذات داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u4-c3-les-molecules-de-defense-dans-le-premier-cas-immunite-non-specifique",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 3,
    chapterAr: "الحزينات الدفاعية في الحالة الأولى",
    chapterFr: "Les molecules de defense dans le premier cas (immunite non specifique)",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الحزينات الدفاعية في الحالة الأولى داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u4-c4-le-complexe-immun",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 4,
    chapterAr: "المعقد المناعي",
    chapterFr: "Le complexe immun",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول المعقد المناعي داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u4-c5-origine-des-anticorps",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 5,
    chapterAr: "مصدر الأجسام المضادة",
    chapterFr: "Origine des anticorps",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل مصدر الأجسام المضادة وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u4-c6-les-elements-de-defense-dans-le-deuxieme-cas-immunite-specifique",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 6,
    chapterAr: "العناصر الدفاعية في الحالة الثانية",
    chapterFr: "Les elements de defense dans le deuxieme cas (immunite specifique)",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول العناصر الدفاعية في الحالة الثانية داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u4-c7-modes-daction-des-lymphocytes-ltc",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 7,
    chapterAr: "طرق تأثير اللمفاويات LTc",
    chapterFr: "Modes d'action des lymphocytes LTc",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل طرق تأثير اللمفاويات LTc وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u4-c8-origine-des-lymphocytes-ltc",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 8,
    chapterAr: "مصدر اللمفاويات LTc",
    chapterFr: "Origine des lymphocytes LTc",
    chapterType: "processus",
    chapterImportance: "haute",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل مصدر اللمفاويات LTc وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u4-c9-activation-des-cellules-lb-et-lt",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 9,
    chapterAr: "تحفيز الخلايا LB و LT",
    chapterFr: "Activation des cellules LB et LT",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل تحفيز الخلايا LB و LT وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u4-c10-choix-du-type-de-reponse-immunitaire",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 10,
    chapterAr: "اختيار نمط الاستجابة المناعية",
    chapterFr: "Choix du type de reponse immunitaire",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول اختيار نمط الاستجابة المناعية داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u4-c11-cause-de-la-perte-de-limmunite-acquise-sida",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 4,
    unitAr: "دور البروتينات في الدفاع عن الذات",
    unitFr: "Role des proteines dans la defense de soi",
    chapterNumero: 11,
    chapterAr: "سبب فقدان المناعة المكتسبة",
    chapterFr: "Cause de la perte de l'immunite acquise (SIDA)",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "immunity-defense-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول سبب فقدان المناعة المكتسبة داخل وحدة دور البروتينات في الدفاع عن الذات.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u5-c1-rappel-des-acquis",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 1,
    chapterAr: "تذكير بالمكتسبات",
    chapterFr: "Rappel des acquis",
    chapterType: "rappel",
    chapterImportance: "moyenne",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استرجاع المكتسبات الأساسية ثم توظيفها داخل وثائق وحدة دور البروتينات في الاتصال العصبي.",
    recommendedVerbs: ["analyse", "justify", "scientific-text"],
  },
  {
    slug: "d1-u5-c2-la-transmission-synaptique-potentiel-membranaire",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 2,
    chapterAr: "النقل المشبكي (الكمون الغشائي)",
    chapterFr: "La transmission synaptique (potentiel membranaire)",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول النقل المشبكي (الكمون الغشائي) داخل وحدة دور البروتينات في الاتصال العصبي.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u5-c3-mecanisme-de-la-transmission-synaptique",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 3,
    chapterAr: "آلية النقل المشبكي",
    chapterFr: "Mecanisme de la transmission synaptique",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل آلية النقل المشبكي وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u5-c4-le-potentiel-de-repos",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 4,
    chapterAr: "كمون الراحة",
    chapterFr: "Le potentiel de repos",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول كمون الراحة داخل وحدة دور البروتينات في الاتصال العصبي.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u5-c5-le-potentiel-daction",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 5,
    chapterAr: "كمون العمل",
    chapterFr: "Le potentiel d'action",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول كمون العمل داخل وحدة دور البروتينات في الاتصال العصبي.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d1-u5-c6-mecanisme-de-lintegration-nerveuse",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 6,
    chapterAr: "آلية الإدماج العصبي",
    chapterFr: "Mecanisme de l'integration nerveuse",
    chapterType: "processus",
    chapterImportance: "haute",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل آلية الإدماج العصبي وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d1-u5-c7-effet-des-drogues-au-niveau-des-synapses",
    domainNumero: 1,
    domainAr: "التخصص الوظيفي للبروتينات",
    domainFr: "La specialisation fonctionnelle des proteines",
    unitNumero: 5,
    unitAr: "دور البروتينات في الاتصال العصبي",
    unitFr: "Role des proteines dans la communication nerveuse",
    chapterNumero: 7,
    chapterAr: "تأثير المخدرات على مستوى المشابك",
    chapterFr: "Effet des drogues au niveau des synapses",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "nervous-communication-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول تأثير المخدرات على مستوى المشابك داخل وحدة دور البروتينات في الاتصال العصبي.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d2-u1-c1-rappel-des-acquis-conditions-et-manifestations-de-la-photosynthese",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 1,
    unitAr: "آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة",
    unitFr: "Mecanismes de conversion de l'energie lumineuse en energie chimique potentielle",
    chapterNumero: 1,
    chapterAr: "تذكير بالمكتسبات",
    chapterFr: "Rappel des acquis (conditions et manifestations de la photosynthese)",
    chapterType: "rappel",
    chapterImportance: "moyenne",
    scenarioId: "photosynthesis-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استرجاع المكتسبات الأساسية ثم توظيفها داخل وثائق وحدة آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة.",
    recommendedVerbs: ["analyse", "justify", "scientific-text"],
  },
  {
    slug: "d2-u1-c2-siege-de-la-photosynthese-ultrastructure-du-chloroplaste",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 1,
    unitAr: "آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة",
    unitFr: "Mecanismes de conversion de l'energie lumineuse en energie chimique potentielle",
    chapterNumero: 2,
    chapterAr: "مقر عملية التركيب الضوئي - ما فوق البنية الخلوية للصانعة الخضراء",
    chapterFr: "Siege de la photosynthese - Ultrastructure du chloroplaste",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "photosynthesis-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول مقر عملية التركيب الضوئي - ما فوق البنية الخلوية للصانعة الخضراء داخل وحدة آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d2-u1-c3-reactions-de-la-phase-photochimique-phase-claire",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 1,
    unitAr: "آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة",
    unitFr: "Mecanismes de conversion de l'energie lumineuse en energie chimique potentielle",
    chapterNumero: 3,
    chapterAr: "تفاعلات المرحلة الكيموضوئية",
    chapterFr: "Reactions de la phase photochimique (phase claire)",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "photosynthesis-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل تفاعلات المرحلة الكيموضوئية وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u1-c4-reactions-de-la-phase-chimique-cycle-de-calvin-phase-sombre",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 1,
    unitAr: "آليات تحويل الطاقة الضوئية إلى طاقة كيميائية كامنة",
    unitFr: "Mecanismes de conversion de l'energie lumineuse en energie chimique potentielle",
    chapterNumero: 4,
    chapterAr: "تفاعلات المرحلة الكيموحيوية",
    chapterFr: "Reactions de la phase chimique (cycle de Calvin - phase sombre)",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "photosynthesis-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل تفاعلات المرحلة الكيموحيوية وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u2-c1-rappel-des-acquis",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 1,
    chapterAr: "تذكير بالمكتسبات",
    chapterFr: "Rappel des acquis",
    chapterType: "rappel",
    chapterImportance: "moyenne",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو استرجاع المكتسبات الأساسية ثم توظيفها داخل وثائق وحدة آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP.",
    recommendedVerbs: ["analyse", "justify", "scientific-text"],
  },
  {
    slug: "d2-u2-c2-siege-de-loxydation-respiratoire",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 2,
    chapterAr: "مقر الأكسدة التنفسية",
    chapterFr: "Siege de l'oxydation respiratoire",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول مقر الأكسدة التنفسية داخل وحدة آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d2-u2-c3-la-glycolyse",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 3,
    chapterAr: "التحلل السكري",
    chapterFr: "La glycolyse",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل التحلل السكري وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u2-c4-etapes-de-degradation-de-lacide-pyruvique-reactions-du-cycle-de-krebs",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 4,
    chapterAr: "مراحل تفكك حمض البيروفيك",
    chapterFr: "Etapes de degradation de l'acide pyruvique (reactions du cycle de Krebs)",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل مراحل تفكك حمض البيروفيك وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u2-c5-la-phosphorylation-oxydative",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 5,
    chapterAr: "الفسفرة التأكسدية",
    chapterFr: "La phosphorylation oxydative",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل الفسفرة التأكسدية وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u2-c6-mecanismes-de-conversion-en-milieu-anaerobie-fermentation",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 2,
    unitAr: "آليات تحويل الطاقة الكيمائية الكامنة في الجزيئات العضوية إلى ATP",
    unitFr: "Mecanismes de conversion de l'energie chimique potentielle des molecules organiques en ATP",
    chapterNumero: 6,
    chapterAr: "آليات تحويل الطاقة الكيميائية الكامنة في وسط لا هوائي",
    chapterFr: "Mecanismes de conversion en milieu anaerobie (fermentation)",
    chapterType: "processus",
    chapterImportance: "haute",
    scenarioId: "cellular-respiration-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل آليات تحويل الطاقة الكيميائية الكامنة في وسط لا هوائي وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d2-u3-c1-les-transformations-energetiques-au-niveau-cellulaire",
    domainNumero: 2,
    domainAr: "التحولات الطاقوية",
    domainFr: "Les transformations energetiques",
    unitNumero: 3,
    unitAr: "تحويل الطاقة على المستوى ما فوق البنية الخلوية",
    unitFr: "Conversion de l'energie au niveau ultrastructural cellulaire",
    chapterNumero: 1,
    chapterAr: "التحولات الطاقوية على المستوى الخلوي",
    chapterFr: "Les transformations energetiques au niveau cellulaire",
    chapterType: "synthese",
    chapterImportance: "critique",
    scenarioId: "ultrastructural-energy-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تركيب نتائج الوثائق في بناء علمي منظم حول التحولات الطاقوية على المستوى الخلوي.",
    recommendedVerbs: ["scientific-text", "compare", "relationship", "deduce"],
  },
  {
    slug: "d3-u1-c1-identification-des-plaques-tectoniques",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 1,
    unitAr: "النشاط التكتوني للصفائح",
    unitFr: "L'activite tectonique des plaques",
    chapterNumero: 1,
    chapterAr: "تحديد الصفائح التكتونية",
    chapterFr: "Identification des plaques tectoniques",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "tectonics-general-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول تحديد الصفائح التكتونية داخل وحدة النشاط التكتوني للصفائح.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u1-c2-mouvements-des-plaques-tectoniques",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 1,
    unitAr: "النشاط التكتوني للصفائح",
    unitFr: "L'activite tectonique des plaques",
    chapterNumero: 2,
    chapterAr: "حركات الصفائح التكتونية",
    chapterFr: "Mouvements des plaques tectoniques",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "tectonics-general-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول حركات الصفائح التكتونية داخل وحدة النشاط التكتوني للصفائح.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u1-c3-lenergie-interne-du-globe-terrestre",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 1,
    unitAr: "النشاط التكتوني للصفائح",
    unitFr: "L'activite tectonique des plaques",
    chapterNumero: 3,
    chapterAr: "الطاقة الداخلية للكرة الأرضية",
    chapterFr: "L'energie interne du globe terrestre",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "tectonics-general-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الطاقة الداخلية للكرة الأرضية داخل وحدة النشاط التكتوني للصفائح.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u2-c1-les-ondes-sismiques",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 2,
    unitAr: "بنية الكرة الأرضية",
    unitFr: "Structure du globe terrestre",
    chapterNumero: 1,
    chapterAr: "الموجات الزلزالية",
    chapterFr: "Les ondes sismiques",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "earth-structure-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الموجات الزلزالية داخل وحدة بنية الكرة الأرضية.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u2-c2-composition-chimique-des-roches-de-la-croute-terrestre-et-du-manteau",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 2,
    unitAr: "بنية الكرة الأرضية",
    unitFr: "Structure du globe terrestre",
    chapterNumero: 2,
    chapterAr: "التركيب الكيميائي لصخور القشرة الأرضية والمعطف",
    chapterFr: "Composition chimique des roches de la croute terrestre et du manteau",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "earth-structure-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول التركيب الكيميائي لصخور القشرة الأرضية والمعطف داخل وحدة بنية الكرة الأرضية.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u2-c3-modelisation-de-la-structure-interne-du-globe-terrestre",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 2,
    unitAr: "بنية الكرة الأرضية",
    unitFr: "Structure du globe terrestre",
    chapterNumero: 3,
    chapterAr: "نمذجة البنية الداخلية للكرة الأرضية",
    chapterFr: "Modelisation de la structure interne du globe terrestre",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "earth-structure-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول نمذجة البنية الداخلية للكرة الأرضية داخل وحدة بنية الكرة الأرضية.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u3-c1-caracteristiques-des-dorsales-medio-oceaniques",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 1,
    chapterAr: "الظواهر المرتبطة بالبناء",
    chapterFr: "Caracteristiques des dorsales medio-oceaniques",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الظواهر المرتبطة بالبناء داخل وحدة النشاط التكتوني والبنيات الجيولوجية المرتبطة به.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u3-c2-le-magmatisme-et-la-formation-de-la-plaque-oceanique",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 2,
    chapterAr: "المغماتية وتشكل اللوح المحيطي",
    chapterFr: "Le magmatisme et la formation de la plaque oceanique",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل المغماتية وتشكل اللوح المحيطي وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d3-u3-c3-formation-des-roches-caracteristiques-de-la-dorsale-medio-oceanique",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 3,
    chapterAr: "تشكل الصخور المميزة للظهرة وسط محيطية",
    chapterFr: "Formation des roches caracteristiques de la dorsale medio-oceanique",
    chapterType: "processus",
    chapterImportance: "haute",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل تشكل الصخور المميزة للظهرة وسط محيطية وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d3-u3-c4-phenomenes-lies-a-la-subduction",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 4,
    chapterAr: "الظواهر المرتبطة بالغوص",
    chapterFr: "Phenomenes lies a la subduction",
    chapterType: "concept",
    chapterImportance: "critique",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول الظواهر المرتبطة بالغوص داخل وحدة النشاط التكتوني والبنيات الجيولوجية المرتبطة به.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u3-c5-disparition-de-la-plaque-oceanique-et-phenomenes-lies-a-la-subduction",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 5,
    chapterAr: "اختفاء اللوح المحيطي والظواهر المرتبطة بالغوص",
    chapterFr: "Disparition de la plaque oceanique et phenomenes lies a la subduction",
    chapterType: "processus",
    chapterImportance: "critique",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو تحليل مراحل اختفاء اللوح المحيطي والظواهر المرتبطة بالغوص وربطها بنتائج الوثائق والمكتسبات العلمية.",
    recommendedVerbs: ["analyse", "interpret", "deduce", "scientific-text"],
  },
  {
    slug: "d3-u3-c6-reliefs-resultant-de-la-collision",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 6,
    chapterAr: "التضاريس الناجمة عن التصادم",
    chapterFr: "Reliefs resultant de la collision",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول التضاريس الناجمة عن التصادم داخل وحدة النشاط التكتوني والبنيات الجيولوجية المرتبطة به.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u3-c7-indices-du-raccourcissement",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 7,
    chapterAr: "شواهد التقلص",
    chapterFr: "Indices du raccourcissement",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول شواهد التقلص داخل وحدة النشاط التكتوني والبنيات الجيولوجية المرتبطة به.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
  {
    slug: "d3-u3-c8-indices-dun-ancien-ocean-ophiolites",
    domainNumero: 3,
    domainAr: "التكتونية العامة",
    domainFr: "La tectonique des plaques",
    unitNumero: 3,
    unitAr: "النشاط التكتوني والبنيات الجيولوجية المرتبطة به",
    unitFr: "L'activite tectonique et les structures geologiques associees",
    chapterNumero: 8,
    chapterAr: "شواهد محيط قديم",
    chapterFr: "Indices d'un ancien ocean (ophiolites)",
    chapterType: "concept",
    chapterImportance: "haute",
    scenarioId: "subduction-collision-ridge-v1",
    focusAr: "التركيز المنهجي في هذا الفصل هو بناء فهم وثائقي مضبوط حول شواهد محيط قديم داخل وحدة النشاط التكتوني والبنيات الجيولوجية المرتبطة به.",
    recommendedVerbs: ["analyse", "interpret", "compare", "relationship"],
  },
]

export function getMethodologyChapterLink(slug: string) {
  return methodologyChapterLinks.find((chapter) => chapter.slug === slug)
}

export function getMethodologyChaptersByScenario(scenarioId: string) {
  return methodologyChapterLinks.filter((chapter) => chapter.scenarioId === scenarioId)
}

export function getMethodologyChaptersByUnit(unitFr: string) {
  return methodologyChapterLinks.filter((chapter) => chapter.unitFr === unitFr)
}
