const GlossaryData = {
  terms: [
    // ===== BIOLOGIE - Lettre A =====
    { fr: "ADN (Acide désoxyribonucléique)", ar: "حمض نووي ريبوزي ناقص الأكسيجين", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "ARN (Acide ribonucléique)", ar: "حمض نووي ريبوزي", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "ARN messager (ARNm)", ar: "حمض ARN رسول", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "ARN de transfert (ARNt)", ar: "ناقل حمض ARN", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Acide aminé", ar: "حمض أميني", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Acide aminé essentiel", ar: "حمض أميني أساسي", category: "biologie", subcategory: "proteines", level: "important" },
    { fr: "Acide pyruvique", ar: "حمض بيروفي", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Acide lactique", ar: "حمض لبني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Acétylcholine", ar: "أسيتيلكولين", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Acétylcoenzyme A", ar: "أسيتيل A مرافق أنزيم", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Absorption", ar: "امتصاص", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Activation", ar: "تنشيط", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Adénosine triphosphate (ATP)", ar: "أدنوزين ثلاثي الفسفات", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Adrénaline", ar: "أدرنالين", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Aérobie", ar: "هوائية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Agglutination", ar: "لكد", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Allèle", ar: "حليل", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Allergie", ar: "أرجية", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Alvéole pulmonaire", ar: "سنخ رئوي", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Amidon", ar: "نشا", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Amylase", ar: "نشواز أميلاز", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Anabolisme", ar: "ابتناء", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Anaérobie", ar: "لاهوائية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Anaphase", ar: "طور انفصالي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Anatomie", ar: "شراحة", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Anémie", ar: "فقر الدم", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Angiospermes", ar: "كاسيات البذور", category: "biologie", subcategory: "botanique", level: "basic" },
    { fr: "Anomalie chromosomique", ar: "شذوذ صبغي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Antibiotique", ar: "مضاد حيوي", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Anticodon", ar: "مضاد الوحدة الرمزية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Anticorps", ar: "جسم مضاد", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Antigène", ar: "مولد المضاد، مستضد", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Antiparallèle", ar: "مضاد التوازي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Appareil de Golgi", ar: "جهاز غولجي", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Appareil digestif", ar: "جهاز هضمي", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Autoradiographie", ar: "تصوير إشعاعي ذاتي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Autosome", ar: "صبغي لا جنسي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Autotrophe", ar: "ذاتي التغذية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Axone", ar: "محورة", category: "biologie", subcategory: "nerveux", level: "essential" },
    // ===== BIOLOGIE - Lettres B-G =====
    { fr: "Biodiversité", ar: "تنوع بيولوجي", category: "biologie", subcategory: "ecologie", level: "important" },
    { fr: "Biomasse", ar: "كتلة حية", category: "biologie", subcategory: "ecologie", level: "basic" },
    { fr: "Biosynthèse", ar: "تخليق حيوي", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Cambium", ar: "كمبيوم", category: "biologie", subcategory: "botanique", level: "basic" },
    { fr: "Capillaire sanguin", ar: "شعيرة دموية", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Capside", ar: "عليبة، كبسيدة", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Caractère", ar: "صفة", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Cil vibratil", ar: "هدب مهتز", category: "biologie", subcategory: "cellule", level: "basic" },
    { fr: "Classification", ar: "تصنيف", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Complexe enzymatique", ar: "مركب أنزيمي", category: "biologie", subcategory: "enzymes", level: "important" },
    { fr: "Composé organique", ar: "مركب عضوي", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Connexion nerveuse", ar: "ارتباط عصبي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Contraction musculaire", ar: "تقلص عضلي", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Croisement", ar: "تزاوج", category: "biologie", subcategory: "genetique", level: "important" },
    // ===== BIOLOGIE - Lettres H-Z =====
    { fr: "Haploïde", ar: "أحادي الصيغة الصبغية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Hétérotrophe", ar: "متباين التغذية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Hétérozygote", ar: "مختلف الاقتران", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Histocompatibilité", ar: "تكامل نسيجي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Histologie", ar: "علم الأنسجة", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Histone", ar: "هيستون", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Homozygote", ar: "متشابه الاقتران", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Hormone", ar: "هرمون", category: "biologie", subcategory: "general", level: "essential" },
    { fr: "Humoral", ar: "خلطي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Hybridation", ar: "تهجين", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Hydrolyse", ar: "حلمأة", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Hydrophile", ar: "محب للماء", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Hydrophobe", ar: "نافر للماء", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Insectes", ar: "حشرات", category: "biologie", subcategory: "zoologie", level: "basic" },
    { fr: "Intégration", ar: "إدماج", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Interphase", ar: "طور بيني", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Intestin grêle", ar: "معي دقيق", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Introns", ar: "دخلونات، أنترونات", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Larve", ar: "يرقة", category: "biologie", subcategory: "zoologie", level: "basic" },
    { fr: "Liaison peptidique", ar: "رابطة بيبتيدية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Liaison phosphodiester", ar: "رابطة فوسفو ثنائي الإستير", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Ligand", ar: "ربيطة", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Monocyte", ar: "وحيدة", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Morphologie", ar: "دراسة الشكل", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Nerf", ar: "عصب", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Neurone", ar: "عصبون", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Noyau", ar: "نواة", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Nucléole", ar: "نوية", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Nucléoside", ar: "نكليوزيد", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Nucléotide", ar: "نكليوتيد", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Organites cellulaires", ar: "عضيات خلوية", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Parasite", ar: "طفيلي", category: "biologie", subcategory: "ecologie", level: "basic" },
    { fr: "Paroi cellulaire", ar: "جدار خلوي", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Pentose", ar: "سكر خماسي", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Peptide", ar: "بيبتيد", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Perméabilité sélective", ar: "نفاذية انتقائية", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Pigment", ar: "صبغة", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Pinocytose", ar: "احتساء خلوي", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Placenta", ar: "مشيمة", category: "biologie", subcategory: "general", level: "important" },
    { fr: "Plasmocyte", ar: "بلاسموسيت", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Plasmolyse", ar: "انكماش، بلسمة", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Pluricellulaire", ar: "عديد الخلايا", category: "biologie", subcategory: "general", level: "basic" },
    { fr: "Protéase", ar: "بروتياز", category: "biologie", subcategory: "enzymes", level: "important" },
    { fr: "Protéine de transport", ar: "بروتين ناقل", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Protéines intégrales", ar: "بروتينات مدمجة", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Récepteur membranaire", ar: "مستقبل غشائي", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Récessif", ar: "متنحي", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Respiration cellulaire", ar: "تنفس خلوي", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Réticulum endoplasmique lisse", ar: "شبكة سيتوبلازمية ملساء", category: "biologie", subcategory: "cellule", level: "important" },
    { fr: "Réticulum endoplasmique rugueux", ar: "شبكة سيتوبلازمية محببة", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Sarcomère", ar: "قسيم عضلي", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Spore", ar: "بوغ", category: "biologie", subcategory: "botanique", level: "basic" },
    { fr: "Stroma", ar: "حشوة، ستروما", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Structure primaire (Protéines)", ar: "بنية أولية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Thymus", ar: "غدة سعترية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Traduction", ar: "ترجمة", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Transcriptase inverse", ar: "ناسخة عكسية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Transcription", ar: "نسخ", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Transport actif", ar: "نقل نشيط", category: "biologie", subcategory: "cellule", level: "essential" },
    { fr: "Virus", ar: "فيروس، حمة", category: "biologie", subcategory: "immunite", level: "essential" },

    // ═══════════════════════════════════════════
    // TERMES MANQUANTS - PROGRAMME BAC ALGÉRIEN
    // ═══════════════════════════════════════════

    // ===== SYNTHÈSE DES PROTÉINES =====
    { fr: "Exon", ar: "إكسون، قطعة دالة", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Intron", ar: "إنترون، قطعة غير دالة", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Épissage (Splicing)", ar: "إلصاق، تجميع الإكسونات", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Spliceosome", ar: "جسيم الإلصاق", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Promoteur", ar: "منطقة محفزة", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Terminateur", ar: "إشارة التوقف (استنساخ)", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Codon", ar: "رامزة (3 نيوكليوتيدات)", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Codon initiateur (AUG)", ar: "رامزة الانطلاق", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Codon stop (UAA, UAG, UGA)", ar: "رامزات التوقف", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Brin matrice", ar: "الخيط القالب", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Brin codant", ar: "الخيط المشفر", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "ARN polymérase", ar: "إنزيم بلمرة الحمض النووي الريبوزي", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Ribosome", ar: "ريبوزوم", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Sous-unité ribosomique", ar: "تحت وحدة ريبوزومية", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Site P (Peptidyl)", ar: "الموقع P (موقع الببتيد)", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Site A (Aminoacyl)", ar: "الموقع A (موقع الحمض الأميني)", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Site E (Exit)", ar: "الموقع E (موقع الخروج)", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Peptidyl transférase", ar: "إنزيم نقل الببتيد", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Polysome (Polyribosome)", ar: "متعدد الريبوزوم", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Aminoacyl-ARNt synthétase", ar: "إنزيم تنشيط الحمض الأميني", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Coiffe (Cap 5')", ar: "غطاء الطرف 5'", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Queue Poly-A", ar: "ذيل عديد الأدينين", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "ARN pré-messager", ar: "حمض نووي ريبوزي رسول أولي", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Dogme central", ar: "العقيدة المركزية للبيولوجيا الجزيئية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Expression génique", ar: "التعبير المورثي", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Code génétique", ar: "الشفرة الوراثية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Dégénérescence du code", ar: "تنكس الشفرة الوراثية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Universalité du code", ar: "عالمية الشفرة الوراثية", category: "biologie", subcategory: "genetique", level: "essential" },
    { fr: "Liaison peptidique", ar: "رابطة ببتيدية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Chaîne polypeptidique", ar: "سلسلة عديدة الببتيد", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Facteur de libération (Release factor)", ar: "عامل التحرير", category: "biologie", subcategory: "genetique", level: "important" },
    { fr: "Translocation", ar: "انزلاق الريبوزوم", category: "biologie", subcategory: "genetique", level: "important" },

    // ===== STRUCTURE-FONCTION DES PROTÉINES =====
    { fr: "Structure primaire", ar: "البنية الأولية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Structure secondaire", ar: "البنية الثانوية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Structure tertiaire", ar: "البنية الثالثية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Structure quaternaire", ar: "البنية الرباعية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Hélice alpha", ar: "حلزون ألفا", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Feuillet bêta", ar: "صفائح بيتا", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Pont disulfure", ar: "رابطة كبريتية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Liaison hydrogène", ar: "رابطة هيدروجينية", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Liaison ionique", ar: "رابطة أيونية", category: "biologie", subcategory: "proteines", level: "important" },
    { fr: "Interaction hydrophobe", ar: "تفاعل كاره للماء", category: "biologie", subcategory: "proteines", level: "important" },
    { fr: "Dénaturation", ar: "تمسخ", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Repliement (Folding)", ar: "طي البروتين", category: "biologie", subcategory: "proteines", level: "important" },
    { fr: "Drépanocytose", ar: "فقر الدم المنجلي", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Hémoglobine", ar: "هيموغلوبين", category: "biologie", subcategory: "proteines", level: "essential" },
    { fr: "Insuline", ar: "أنسولين", category: "biologie", subcategory: "proteines", level: "important" },

    // ===== ENZYMOLOGIE =====
    { fr: "Enzyme", ar: "إنزيم", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Substrat", ar: "ركيزة", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Site actif", ar: "الموقع الفعال", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Site de fixation", ar: "موقع التعرف (التثبيت)", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Site catalytique", ar: "موقع التحفيز", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Complexe enzyme-substrat", ar: "معقد إنزيم-ركيزة", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Biocatalyseur", ar: "محفز حيوي", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Énergie d'activation", ar: "طاقة التنشيط", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "pH optimal", ar: "الأس الهيدروجيني الأمثل", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Température optimale", ar: "درجة الحرارة المثلى", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Spécificité de substrat", ar: "النوعية للركيزة", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Spécificité d'action", ar: "النوعية للتفاعل", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Modèle clé-serrure (Fischer)", ar: "نموذج القفل والمفتاح", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Ajustement induit (Koshland)", ar: "التوافق المحدث", category: "biologie", subcategory: "enzymes", level: "essential" },
    { fr: "Inhibiteur compétitif", ar: "مثبط تنافسي", category: "biologie", subcategory: "enzymes", level: "important" },
    { fr: "Inhibiteur non compétitif", ar: "مثبط غير تنافسي", category: "biologie", subcategory: "enzymes", level: "important" },
    { fr: "Alpha-amanitine", ar: "ألفا أمانيتين (مثبط ARN polymérase)", category: "biologie", subcategory: "enzymes", level: "important" },

    // ===== IMMUNOLOGIE =====
    { fr: "Lymphocyte B (LB)", ar: "لمفاوية B", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Lymphocyte T4 (LTh)", ar: "لمفاوية T4 مساعدة", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Lymphocyte T8 (LTc)", ar: "لمفاوية T8 سامة", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Cellule présentatrice d'antigène (CPA)", ar: "خلية عارضة للمولد الضدي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "CMH de classe I", ar: "معقد التوافق النسيجي الرئيسي صنف I", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "CMH de classe II", ar: "معقد التوافق النسيجي الرئيسي صنف II", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "HLA (Human Leukocyte Antigen)", ar: "مستضد الكريات البيضاء البشرية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Interleukine (IL-2)", ar: "إنترلوكين", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Perforine", ar: "البرفورين (بروتين الثقب)", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Granzyme", ar: "جرانزيم (إنزيم القتل)", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Apoptose", ar: "الموت الخلوي المبرمج", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Nécrose", ar: "النخر (الموت الخلوي العشوائي)", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Immunité innée (non spécifique)", ar: "مناعة فطرية (غير نوعية)", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Immunité acquise (adaptative)", ar: "مناعة مكتسبة (نوعية)", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Immunité humorale", ar: "مناعة خلطية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Immunité cellulaire", ar: "مناعة خلوية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Phagocytose", ar: "بلعمة", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Macrophage", ar: "بلعمية كبيرة", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Cellule dendritique", ar: "خلية تغصنية", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Réaction inflammatoire", ar: "الاستجابة الالتهابية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Complexe immun", ar: "المعقد المناعي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Immunoglobuline (Ig)", ar: "غلوبيلين مناعي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Sélection clonale", ar: "الانتقاء النسيلي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Expansion clonale", ar: "التكاثر النسيلي", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Cellule mémoire", ar: "خلية ذاكرة", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Épitope (déterminant antigénique)", ar: "محدد مستضدي", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Paratope", ar: "موقع تثبيت المستضد", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Opsonisation", ar: "الأوبسنة (تسهيل البلعمة)", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Neutralisation", ar: "التحييد", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Complément (système)", ar: "المتممة (نظام)", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Réponse primaire", ar: "استجابة أولية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Réponse secondaire", ar: "استجابة ثانوية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Vaccination", ar: "تلقيح", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Le soi", ar: "الذات", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Le non-soi", ar: "اللاذات", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "VIH (Virus de l'Immunodéficience Humaine)", ar: "فيروس نقص المناعة البشرية", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "SIDA", ar: "متلازمة نقص المناعة المكتسب", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "CD4", ar: "مستقبل CD4", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "CD8", ar: "مستقبل CD8", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "TCR (T Cell Receptor)", ar: "مستقبل الخلية T", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "BCR (B Cell Receptor)", ar: "مستقبل الخلية B", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "Rétrovirus", ar: "فيروس قهقري", category: "biologie", subcategory: "immunite", level: "essential" },
    { fr: "gp120", ar: "بروتين سطحي gp120", category: "biologie", subcategory: "immunite", level: "important" },
    { fr: "Infection opportuniste", ar: "عدوى انتهازية", category: "biologie", subcategory: "immunite", level: "important" },

    // ===== COMMUNICATION NERVEUSE =====
    { fr: "Potentiel de repos", ar: "كمون الراحة", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Potentiel d'action", ar: "كمون العمل", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Dépolarisation", ar: "زوال الاستقطاب", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Repolarisation", ar: "إعادة الاستقطاب", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Hyperpolarisation", ar: "فرط الاستقطاب", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Seuil d'excitation", ar: "عتبة التنبيه", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Loi du tout ou rien", ar: "قانون الكل أو لا شيء", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Codage en fréquence", ar: "الترميز الترددي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Période réfractaire", ar: "فترة الجموح", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Synapse chimique", ar: "مشبك كيميائي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Fente synaptique", ar: "الشق المشبكي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Vésicule synaptique", ar: "حويصلة مشبكية", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Neurotransmetteur", ar: "ناقل عصبي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Élément pré-synaptique", ar: "العنصر قبل المشبكي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Élément post-synaptique", ar: "العنصر بعد المشبكي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "PPSE (Potentiel post-synaptique excitateur)", ar: "كمون بعد مشبكي منبه", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "PPSI (Potentiel post-synaptique inhibiteur)", ar: "كمون بعد مشبكي مثبط", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Sommation temporelle", ar: "إدماج زمني", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Sommation spatiale", ar: "إدماج مكاني", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Cône axonique", ar: "تل المحور", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Gaine de myéline", ar: "غمد الميالين", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Nœud de Ranvier", ar: "عقدة رانفييه", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Conduction saltatoire", ar: "انتشار قفزي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Conduction continue", ar: "انتشار متواصل", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Pompe Na+/K+ ATPase", ar: "مضخة الصوديوم والبوتاسيوم", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Canal ionique voltage-dépendant", ar: "قناة أيونية ذات بوابة جهدية", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Canal ionique chimio-dépendant", ar: "قناة أيونية ذات بوابة كيميائية", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Dopamine", ar: "دوبامين", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "GABA", ar: "حمض غاما أمينوبيوتيريك (ناقل مثبط)", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Sérotonine", ar: "سيروتونين", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Endorphine", ar: "إندورفين", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Agoniste", ar: "ناهض (مقلد للناقل)", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Antagoniste", ar: "مناهض (حاجب للمستقبل)", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Addiction", ar: "إدمان", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Circuit de récompense", ar: "دارة المكافأة", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Dendrite", ar: "تشجرة", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Corps cellulaire (Soma)", ar: "الجسم الخلوي", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Bouton synaptique", ar: "نهاية مشبكية", category: "biologie", subcategory: "nerveux", level: "essential" },
    { fr: "Acétylcholinestérase", ar: "إنزيم تحلل الأسيتيل كولين", category: "biologie", subcategory: "nerveux", level: "important" },
    { fr: "Recapture (réabsorption)", ar: "إعادة الامتصاص", category: "biologie", subcategory: "nerveux", level: "important" },

    // ===== PHOTOSYNTHÈSE =====
    { fr: "Chloroplaste", ar: "صانعة خضراء", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Chlorophylle", ar: "كلوروفيل (صبغة خضراء)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Thylakoïde", ar: "ثايلاكويد (كيس غشائي)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Granum (pl. Grana)", ar: "غرانوم (كومة ثايلاكويدات)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Lumen (thylakoïde)", ar: "اللومن (فراغ الثايلاكويد)", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Phase photochimique (claire)", ar: "المرحلة الكيموضوئية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Phase chimique (sombre / Calvin)", ar: "المرحلة الكيموحيوية (دورة كالفن)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Photosystème I (PSI / P700)", ar: "النظام الضوئي الأول", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Photosystème II (PSII / P680)", ar: "النظام الضوئي الثاني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Photolyse de l'eau", ar: "التحلل الضوئي للماء", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Chaîne de transport d'électrons", ar: "سلسلة النقل الإلكتروني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Photophosphorylation", ar: "الفسفرة الضوئية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "RuBisCO", ar: "إنزيم تثبيت ثاني أكسيد الكربون", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "RuBP (Ribulose-1,5-bisphosphate)", ar: "ريبيولوز ثنائي الفوسفات", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "APG (Acide phosphoglycérique)", ar: "حمض الفوسفوغليسيريك", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "G3P (Glycéraldéhyde-3-phosphate)", ar: "غليسرالديهيد-3-فوسفات", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "NADPH,H+", ar: "نيكوتيناميد أدينين ثنائي النيكلوتيد فوسفات المرجع", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "ATP synthase", ar: "إنزيم تركيب الـ ATP", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Chimiosmose", ar: "الكيموزموزية (تدرج بروتوني)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Spectre d'absorption", ar: "طيف الامتصاص", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Spectre d'action", ar: "طيف العمل", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Caroténoïdes", ar: "الكاروتينات (صبغات مساعدة)", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Stomate", ar: "ثغرة", category: "biologie", subcategory: "energie", level: "important" },

    // ===== RESPIRATION CELLULAIRE =====
    { fr: "Mitochondrie", ar: "ميتوكوندري", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Matrice mitochondriale", ar: "الماتريكس (سائل الميتوكوندري)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Crêtes mitochondriales", ar: "الكريستا (الغشاء الداخلي المطوي)", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Glycolyse", ar: "التحلل السكري", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Cycle de Krebs", ar: "حلقة كريبس", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Phosphorylation oxydative", ar: "الفسفرة التأكسدية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Chaîne respiratoire", ar: "السلسلة التنفسية", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Acétyl-CoA", ar: "أسيتيل مرافق الإنزيم أ", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "NAD+ / NADH,H+", ar: "ناقل إلكترونات مرجع / مؤكسد", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "FAD / FADH2", ar: "ناقل إلكترونات فلافيني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Oxaloacétate", ar: "أوكسالوأسيتات", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Citrate", ar: "سيترات", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Pyruvate déshydrogénase", ar: "إنزيم نزع هيدروجين البيروفات", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "Fermentation lactique", ar: "تخمر لبني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Fermentation alcoolique", ar: "تخمر كحولي", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Gradient de protons", ar: "تدرج بروتوني", category: "biologie", subcategory: "energie", level: "essential" },
    { fr: "Endosymbiose", ar: "التعايش الداخلي", category: "biologie", subcategory: "energie", level: "important" },
    { fr: "ADN mitochondrial", ar: "الحمض النووي الميتوكوندري", category: "biologie", subcategory: "energie", level: "important" },

    // ===== TECTONIQUE ET GÉOLOGIE =====
    { fr: "Plaque tectonique", ar: "صفيحة تكتونية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Lithosphère", ar: "الغلاف الصخري", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Asthénosphère", ar: "الأستينوسفير (الطبقة اللزجة)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Croûte continentale", ar: "القشرة القارية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Croûte océanique", ar: "القشرة المحيطية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Manteau", ar: "المعطف", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Noyau externe (liquide)", ar: "النواة الخارجية (سائلة)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Noyau interne (solide)", ar: "النواة الداخلية (صلبة)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Discontinuité de Mohorovičić (Moho)", ar: "انقطاع موهو", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Discontinuité de Gutenberg", ar: "انقطاع غوتنبرغ", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Discontinuité de Lehmann", ar: "انقطاع ليمان", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Onde P (Primaire)", ar: "موجات P (طولية)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Onde S (Secondaire)", ar: "موجات S (مستعرضة)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Sismographe", ar: "جهاز قياس الزلازل", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Divergence (frontière)", ar: "حدود تباعدية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Convergence (frontière)", ar: "حدود تقاربية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Faille transformante", ar: "فالق تحويلي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Subduction", ar: "غوص", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Collision continentale", ar: "تصادم قاري", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Dorsale médio-océanique", ar: "ظهرة وسط محيطية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Rift axial", ar: "وادي متصدع مركزي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Fosse océanique", ar: "خندق محيطي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Plan de Benioff", ar: "نطاق بنيوف", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Granite", ar: "غرانيت", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Basalte", ar: "بازلت", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Gabbro", ar: "غابرو", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Péridotite", ar: "بيريدوتيت", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Olivine", ar: "أوليفين", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Pyroxène", ar: "بيروكسين", category: "geologie", subcategory: "roches", level: "important" },
    { fr: "Plagioclase", ar: "بلاجيوكلاز", category: "geologie", subcategory: "roches", level: "important" },
    { fr: "Quartz", ar: "كوارتز", category: "geologie", subcategory: "roches", level: "important" },
    { fr: "Feldspath", ar: "فلدسبات", category: "geologie", subcategory: "roches", level: "important" },
    { fr: "SIAL (Silice-Aluminium)", ar: "سيال (قشرة قارية)", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "SIMA (Silice-Magnésium)", ar: "سيما (قشرة محيطية)", category: "geologie", subcategory: "roches", level: "essential" },
    { fr: "Ophiolite", ar: "أوفيوليت (بقايا قشرة محيطية)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Pillow lava (Basalte en coussins)", ar: "بازلت وسادي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Séquence ophiolitique", ar: "التسلسل الأوفيوليتي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Fusion partielle", ar: "انصهار جزئي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Décompression adiabatique", ar: "انخفاض الضغط اللاحراري", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Magma basaltique", ar: "صهارة بازلتية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Magma andésitique", ar: "صهارة أنديزيتية", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Convection (courants)", ar: "تيارات الحمل الحراري", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Flux géothermique", ar: "التدفق الحراري الأرضي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Radioactivité (source de chaleur)", ar: "التفكك الإشعاعي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Ridge push", ar: "دفع من الظهرة", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Slab pull", ar: "سحب اللوح الغاطس", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Paléomagnétisme", ar: "المغناطيسية القديمة", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Anomalie magnétique", ar: "شذوذ مغناطيسي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Isostasie", ar: "التوازن التعويضي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Métamorphisme", ar: "تحول صخري", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Schiste vert", ar: "شيست أخضر", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Schiste bleu", ar: "شيست أزرق", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Éclogite", ar: "إكلوجيت", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Glaucophane", ar: "غلوكوفان (معدن أزرق)", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Grenat", ar: "جارنيت (معدن أحمر)", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Obduction", ar: "ارتفاع القشرة المحيطية على القارة", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Pli (Anticlinal)", ar: "طية محدبة", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Pli (Synclinal)", ar: "طية مقعرة", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Faille inverse", ar: "فالق عكسي", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Faille normale", ar: "فالق طبيعي", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Chevauchement", ar: "تراكب", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Raccourcissement", ar: "تقلص", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Champ magnétique terrestre", ar: "المجال المغناطيسي للأرض", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Pangée", ar: "بانجيا (القارة العملاقة)", category: "geologie", subcategory: "tectonique", level: "important" },
    { fr: "Téthys", ar: "محيط تيثيس (القديم)", category: "geologie", subcategory: "tectonique", level: "essential" },
    { fr: "Wegener", ar: "ألفريد فيغنر (نظرية الانجراف)", category: "geologie", subcategory: "tectonique", level: "important" },

    // ===== CHIMIE =====
    { fr: "Oxydant", ar: "مؤكسد", category: "chimie", subcategory: "reactions", level: "important" },
    { fr: "Oxydation", ar: "أكسدة", category: "chimie", subcategory: "reactions", level: "essential" },
    { fr: "pH", ar: "الأس الهيدروجيني", category: "chimie", subcategory: "general", level: "essential" },
    { fr: "Photosynthèse", ar: "التمثيل الضوئي", category: "chimie", subcategory: "biochimie", level: "essential" },
    { fr: "Réducteur", ar: "مختزل", category: "chimie", subcategory: "reactions", level: "important" },
    { fr: "Réduction", ar: "اختزال", category: "chimie", subcategory: "reactions", level: "important" },
    { fr: "Solution", ar: "محلول", category: "chimie", subcategory: "general", level: "basic" },

    // ═══════════════════════════════════════════
    // TERMES MÉTHODOLOGIQUES BAC
    // Verbes de consignes et vocabulaire d'examen
    // ═══════════════════════════════════════════

    // ===== VERBES DE CONSIGNES (les plus importants !) =====
    {
      fr: "Analyser",
      ar: "حلّل",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Étudier un document en détail pour en extraire les informations importantes et les mettre en relation.",
      definition_ar: "دراسة وثيقة بالتفصيل لاستخراج المعلومات المهمة وربطها ببعض.",
      exemple: "حلّل المنحنى البياني: 1) صف ما تلاحظه 2) فسّر التغيرات 3) استنتج"
    },
    {
      fr: "Comparer",
      ar: "قارن",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Mettre en évidence les ressemblances ET les différences entre deux éléments.",
      definition_ar: "إظهار أوجه التشابه والاختلاف بين عنصرين أو أكثر.",
      exemple: "قارن = التشابهات أولاً + الاختلافات ثانياً. استخدم جدولاً!"
    },
    {
      fr: "Décrire",
      ar: "صِف",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Dire ce qu'on observe sans interpréter ni expliquer.",
      definition_ar: "ذكر ما نلاحظه بدقة دون تفسير أو شرح.",
      exemple: "صف = ماذا ترى؟ فقط! لا تقل لماذا"
    },
    {
      fr: "Déduire",
      ar: "استنتج",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Tirer une conclusion logique à partir des données ou des résultats observés.",
      definition_ar: "استخلاص نتيجة منطقية من المعطيات أو النتائج الملاحظة.",
      exemple: "استنتج = إذن... / وبالتالي... / نستخلص أن..."
    },
    {
      fr: "Expliquer",
      ar: "فسّر / اشرح",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Donner les raisons et les mécanismes d'un phénomène observé.",
      definition_ar: "إعطاء الأسباب والآليات لظاهرة ملاحظة.",
      exemple: "فسّر = لماذا؟ / السبب هو... / يُفسَّر ذلك بـ..."
    },
    {
      fr: "Justifier",
      ar: "علّل / برّر",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Prouver une affirmation en donnant des arguments scientifiques ou des données.",
      definition_ar: "إثبات قول ما بتقديم حجج علمية أو معطيات.",
      exemple: "علّل = لأن... / الدليل هو... / يتضح ذلك من..."
    },
    {
      fr: "Interpréter",
      ar: "فسّر / أوّل",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Donner une signification scientifique à un résultat observé en utilisant ses connaissances.",
      definition_ar: "إعطاء معنى علمي لنتيجة ملاحظة باستخدام المعارف.",
      exemple: "فسّر النتيجة = هذا يعني أن... / يدل على... / يُعبّر عن..."
    },
    {
      fr: "Schématiser",
      ar: "ارسم تخطيطياً",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Représenter par un dessin simplifié et annoté.",
      definition_ar: "تمثيل بواسطة رسم مبسط مع تسميات.",
      exemple: "ارسم = عنوان + رسم واضح + تسميات + أسهم + مفتاح"
    },
    {
      fr: "Identifier",
      ar: "حدّد / عيّن",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Reconnaître et nommer un élément précis.",
      definition_ar: "التعرف على عنصر محدد وتسميته.",
      exemple: "حدّد = هو... / يتعلق بـ... / المعني هو..."
    },
    {
      fr: "Définir",
      ar: "عرّف",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Donner une définition précise et concise d'un terme scientifique.",
      definition_ar: "إعطاء تعريف دقيق ومختصر لمصطلح علمي.",
      exemple: "عرّف = هو/هي... + الخصائص + الدور"
    },
    {
      fr: "Proposer une hypothèse",
      ar: "اقترح فرضية",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Formuler une explication possible et vérifiable d'un phénomène.",
      definition_ar: "صياغة تفسير محتمل وقابل للتحقق لظاهرة ما.",
      exemple: "الفرضية = نفترض أن... / يمكن أن يكون السبب هو..."
    },
    {
      fr: "Rédiger un texte scientifique",
      ar: "حرّر نصاً علمياً",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Écrire un texte organisé avec introduction, développement et conclusion.",
      definition_ar: "كتابة نص منظم بمقدمة وعرض وخاتمة.",
      exemple: "النص العلمي = مقدمة (تعريف + إشكالية) + عرض (فقرات) + خاتمة"
    },
    {
      fr: "Montrer / Démontrer",
      ar: "بيّن / أثبت",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Prouver quelque chose en s'appuyant sur des faits ou des données.",
      definition_ar: "إثبات شيء بالاعتماد على معطيات أو حقائق.",
      exemple: "بيّن = الدليل هو... / يتضح من الوثيقة أن..."
    },
    {
      fr: "Nommer / Citer",
      ar: "سمّ / اذكر",
      category: "methodologie",
      subcategory: "consignes",
      level: "essential",
      definition_fr: "Donner le nom exact sans développer.",
      definition_ar: "ذكر الاسم الدقيق بدون تفصيل.",
      exemple: "اذكر = فقط الأسماء! لا تشرح"
    },
    {
      fr: "Résumer",
      ar: "لخّص",
      category: "methodologie",
      subcategory: "consignes",
      level: "important",
      definition_fr: "Reprendre les idées essentielles de façon brève.",
      definition_ar: "إعادة الأفكار الأساسية بشكل مختصر.",
      exemple: "لخّص = الأفكار الرئيسية فقط، بدون تفاصيل"
    },
    {
      fr: "Calculer",
      ar: "احسب",
      category: "methodologie",
      subcategory: "consignes",
      level: "important",
      definition_fr: "Effectuer un calcul numérique avec les données fournies.",
      definition_ar: "إجراء حساب رقمي بالمعطيات المقدمة.",
      exemple: "احسب = المعطيات + العملية + النتيجة + الوحدة"
    },
    {
      fr: "Représenter graphiquement",
      ar: "مثّل بيانياً",
      category: "methodologie",
      subcategory: "consignes",
      level: "important",
      definition_fr: "Tracer un graphique à partir de données.",
      definition_ar: "رسم منحنى أو رسم بياني من المعطيات.",
      exemple: "مثّل = عنوان + محور الأفاصيل + محور الأراتيب + وحدات + نقاط + منحنى"
    },

    // ===== DÉMARCHE SCIENTIFIQUE =====
    {
      fr: "Hypothèse",
      ar: "فرضية",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Proposition d'explication provisoire d'un phénomène, à vérifier par l'expérimentation.",
      definition_ar: "اقتراح تفسير مؤقت لظاهرة، يجب التحقق منه بالتجربة.",
      exemple: "الفرضية العلمية = تخمين مدروس + قابل للاختبار"
    },
    {
      fr: "Expérience témoin",
      ar: "تجربة شاهدة",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Expérience de référence sans le facteur étudié, pour comparer les résultats.",
      definition_ar: "تجربة مرجعية بدون العامل المدروس، للمقارنة.",
      exemple: "التجربة الشاهدة = لا نغير فيها أي عامل (نقطة المقارنة)"
    },
    {
      fr: "Variable",
      ar: "متغير",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Facteur qui peut changer dans une expérience.",
      definition_ar: "عامل يمكن أن يتغير في تجربة.",
      exemple: "المتغير = العامل الوحيد الذي نغيّره في التجربة"
    },
    {
      fr: "Protocole expérimental",
      ar: "بروتوكول تجريبي",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Description détaillée des étapes d'une expérience.",
      definition_ar: "وصف مفصل لخطوات تجربة ما.",
      exemple: "البروتوكول = 1) الأدوات 2) الخطوات 3) القياسات"
    },
    {
      fr: "Résultat expérimental",
      ar: "نتيجة تجريبية",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Ce qui est observé ou mesuré à la fin d'une expérience.",
      definition_ar: "ما يُلاحظ أو يُقاس في نهاية التجربة.",
      exemple: "النتيجة = القيم + الملاحظات + (جدول أو رسم بياني)"
    },
    {
      fr: "Conclusion",
      ar: "استنتاج، خلاصة",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Synthèse finale qui répond à la problématique posée.",
      definition_ar: "خلاصة نهائية تجيب على الإشكالية المطروحة.",
      exemple: "الخلاصة = نجيب على السؤال المطروح في البداية"
    },
    {
      fr: "Problématique",
      ar: "إشكالية",
      category: "methodologie",
      subcategory: "demarche",
      level: "essential",
      definition_fr: "Question scientifique à laquelle on cherche à répondre.",
      definition_ar: "سؤال علمي نسعى للإجابة عنه.",
      exemple: "الإشكالية = سؤال رئيسي يوجه البحث بأكمله"
    },

    // ===== OUTILS ET MATÉRIEL =====
    {
      fr: "Microscope optique",
      ar: "مجهر ضوئي",
      category: "methodologie",
      subcategory: "outils",
      level: "essential",
      definition_fr: "Instrument utilisant la lumière visible pour observer des structures cellulaires.",
      definition_ar: "جهاز يستخدم الضوء المرئي لملاحظة البنيات الخلوية.",
      exemple: "التكبير حتى ×1000، يستخدم لرؤية الخلايا والأنوية"
    },
    {
      fr: "Microscope électronique",
      ar: "مجهر إلكتروني",
      category: "methodologie",
      subcategory: "outils",
      level: "essential",
      definition_fr: "Instrument utilisant un faisceau d'électrons pour une résolution très élevée.",
      definition_ar: "جهاز يستخدم حزمة إلكترونات لدقة عالية جداً.",
      exemple: "التكبير حتى ×500000، يرى العضيات والجزيئات"
    },
    {
      fr: "Lame et lamelle",
      ar: "صفيحة ورقاقة مجهرية",
      category: "methodologie",
      subcategory: "outils",
      level: "basic",
      definition_fr: "Support en verre pour observer un échantillon au microscope.",
      definition_ar: "حامل زجاجي لملاحظة عينة تحت المجهر.",
      exemple: "توضع العينة بين الصفيحة والرقاقة للمشاهدة"
    },
    {
      fr: "Colorant (Lugol, Bleu de méthylène)",
      ar: "ملون (لوغول، أزرق الميثيلين)",
      category: "methodologie",
      subcategory: "outils",
      level: "important",
      definition_fr: "Substance utilisée pour rendre visibles certaines structures cellulaires.",
      definition_ar: "مادة تُستخدم لإظهار بنيات خلوية معينة.",
      exemple: "لوجول = لون النشا إلى أزرق-بنفسجي / أزرق الميثيلين = يلون النواة"
    },
    {
      fr: "Autoradiographie",
      ar: "تصوير إشعاعي ذاتي",
      category: "methodologie",
      subcategory: "outils",
      level: "essential",
      definition_fr: "Technique utilisant des isotopes radioactifs pour localiser des molécules dans la cellule.",
      definition_ar: "تقنية تستخدم نظائر مشعة لتحديد موقع الجزيئات في الخلية.",
      exemple: "لتتبع جزيء معين (مثال: تتبع ADN الموسوم)"
    },
    {
      fr: "Électrophorèse",
      ar: "الرحلان الكهربائي",
      category: "methodologie",
      subcategory: "outils",
      level: "important",
      definition_fr: "Technique de séparation des molécules selon leur taille et charge électrique.",
      definition_ar: "تقنية فصل الجزيئات حسب حجمها وشحنتها الكهربائية.",
      exemple: "تفصل ADN أو بروتينات على هلام أغاروز"
    },
    {
      fr: "Centrifugation",
      ar: "طرد مركزي",
      category: "methodologie",
      subcategory: "outils",
      level: "important",
      definition_fr: "Technique de séparation par force centrifuge.",
      definition_ar: "تقنية فصل بالقوة المركزية.",
      exemple: "تفصل مكونات الخلية حسب كثافتها"
    },
    {
      fr: "Logiciel Anagene",
      ar: "برنامج أناجين",
      category: "methodologie",
      subcategory: "outils",
      level: "important",
      definition_fr: "Logiciel de comparaison de séquences d'ADN et de protéines.",
      definition_ar: "برنامج مقارنة تتابعات ADN والبروتينات.",
      exemple: "يُستخدم في BAC SVT لمقارنة تسلسلات النيوكليوتيدات"
    },
    {
      fr: "Logiciel Rastop / Rasmol",
      ar: "برنامج راستوب / رازمول",
      category: "methodologie",
      subcategory: "outils",
      level: "important",
      definition_fr: "Logiciel de visualisation 3D des molécules biologiques.",
      definition_ar: "برنامج عرض ثلاثي الأبعاد للجزيئات البيولوجية.",
      exemple: "يُستخدم لعرض البروتينات والأحماض النووية ثلاثية الأبعاد"
    },

    // ===== VOCABULAIRE DE RÉDACTION =====
    {
      fr: "Introduction",
      ar: "مقدمة",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Début du texte qui présente le sujet et pose la problématique.",
      definition_ar: "بداية النص التي تُقدم الموضوع وتطرح الإشكالية.",
      exemple: "المقدمة = عرض الموضوع + الإشكالية + الخطة"
    },
    {
      fr: "Développement",
      ar: "عرض، تطوير",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Corps du texte avec les arguments et les explications.",
      definition_ar: "جسم النص مع الحجج والتفسيرات.",
      exemple: "العرض = فقرات منظمة مع روابط منطقية"
    },
    {
      fr: "Connecteur logique",
      ar: "رابط منطقي",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Mot de liaison entre les idées (car, donc, en effet, de plus...).",
      definition_ar: "كلمة ربط بين الأفكار (لأن، إذن، بالتالي، بالإضافة...).",
      exemple: "الروابط = لأن (سبب) / إذن (نتيجة) / بالإضافة (إضافة)"
    },
    {
      fr: "Légende (schéma)",
      ar: "مفتاح / تسمية (رسم)",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Texte qui explique les symboles et couleurs d'un schéma.",
      definition_ar: "نص يشرح الرموز والألوان في رسم تخطيطي.",
      exemple: "المفتاح = كل لون له دلالة + شرح الرموز"
    },
    {
      fr: "Titre (graphique)",
      ar: "عنوان (رسم بياني)",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Phrase décrivant le contenu d'un graphique ou schéma.",
      definition_ar: "جملة تصف محتوى رسم بياني أو تخطيطي.",
      exemple: "العنوان = ماذا يمثل؟ + في أي ظروف؟"
    },
    {
      fr: "Abscisse (axe X)",
      ar: "محور الأفاصيل",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Axe horizontal d'un graphique.",
      definition_ar: "المحور الأفقي للرسم البياني.",
      exemple: "محور X = المتغير المستقل (الزمن، التركيز...)"
    },
    {
      fr: "Ordonnée (axe Y)",
      ar: "محور الأراتيب",
      category: "methodologie",
      subcategory: "redaction",
      level: "essential",
      definition_fr: "Axe vertical d'un graphique.",
      definition_ar: "المحور العمودي للرسم البياني.",
      exemple: "محور Y = المتغير التابع (النتائج المقاسة)"
    },
    {
      fr: "Échelle",
      ar: "سلم، مقياس",
      category: "methodologie",
      subcategory: "redaction",
      level: "important",
      definition_fr: "Rapport entre les dimensions sur le schéma et les dimensions réelles.",
      definition_ar: "النسبة بين الأبعاد على الرسم والأبعاد الحقيقية.",
      exemple: "السلم = 1 سم → 10 ميكرومتر مثلاً"
    },

    // ===== EXPRESSIONS UTILES POUR LE BAC =====
    {
      fr: "D'après le document",
      ar: "حسب الوثيقة / من خلال الوثيقة",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une information extraite d'un document.",
      definition_ar: "عبارة لتقديم معلومة مستخرجة من وثيقة.",
      exemple: "مثال: حسب الوثيقة 1، نلاحظ أن تركيز ADN يرتفع..."
    },
    {
      fr: "On observe que...",
      ar: "نلاحظ أن...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une observation.",
      definition_ar: "عبارة لتقديم ملاحظة.",
      exemple: "نلاحظ أن المنحنى يرتفع بين t1 و t2"
    },
    {
      fr: "Cela signifie que...",
      ar: "هذا يعني أن...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une interprétation.",
      definition_ar: "عبارة لتقديم تفسير.",
      exemple: "هذا يعني أن الإنزيم يعمل بشكل أفضل عند 37°C"
    },
    {
      fr: "On en déduit que...",
      ar: "نستنتج أن... / إذن...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une conclusion.",
      definition_ar: "عبارة لتقديم استنتاج.",
      exemple: "نستنتج أن المادة X ضرورية لعملية النسخ"
    },
    {
      fr: "Par conséquent...",
      ar: "وبالتالي... / نتيجة لذلك...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une conséquence logique.",
      definition_ar: "عبارة لتقديم نتيجة منطقية.",
      exemple: "وبالتالي، فإن غياب الأكسجين يوقف التنفس الخلوي"
    },
    {
      fr: "En comparant...",
      ar: "بمقارنة... / عند المقارنة...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire une comparaison.",
      definition_ar: "عبارة لتقديم مقارنة.",
      exemple: "بمقارنة الوثيقتين 1 و 2، نلاحظ أن..."
    },
    {
      fr: "Contrairement à...",
      ar: "على عكس... / بخلاف...",
      category: "methodologie",
      subcategory: "expressions",
      level: "important",
      definition_fr: "Expression pour marquer une opposition.",
      definition_ar: "عبارة لإظهار تعارض.",
      exemple: "على عكس الخلية الحيوانية، تحتوي الخلية النباتية على جدار خلوي"
    },
    {
      fr: "En effet...",
      ar: "فعلاً... / في الواقع...",
      category: "methodologie",
      subcategory: "expressions",
      level: "important",
      definition_fr: "Expression pour confirmer ou appuyer une idée.",
      definition_ar: "عبارة لتأكيد أو دعم فكرة.",
      exemple: "فعلاً، تزداد سرعة التفاعل مع ارتفاع التركيز"
    },
    {
      fr: "De plus...",
      ar: "بالإضافة إلى ذلك... / علاوة على...",
      category: "methodologie",
      subcategory: "expressions",
      level: "important",
      definition_fr: "Expression pour ajouter un argument.",
      definition_ar: "عبارة لإضافة حجة.",
      exemple: "علاوة على ذلك، تلعب البروتينات دوراً في الدفاع المناعي"
    },
    {
      fr: "En conclusion...",
      ar: "في الختام... / خلاصة القول...",
      category: "methodologie",
      subcategory: "expressions",
      level: "essential",
      definition_fr: "Expression pour introduire la conclusion finale.",
      definition_ar: "عبارة لتقديم الخلاصة النهائية.",
      exemple: "خلاصة القول، يمكننا القول أن الطاقة تُخزَّن في جزيئات ATP"
    }
  ],

  search(query) {
    const lower = query.toLowerCase();
    return this.terms.filter(t =>
      t.fr.toLowerCase().includes(lower) ||
      t.ar.includes(query)
    );
  },

  getByCategory(category) {
    return this.terms.filter(t => t.category === category);
  },

  getBySubcategory(subcategory) {
    return this.terms.filter(t => t.subcategory === subcategory);
  },

  getByLevel(level) {
    return this.terms.filter(t => t.level === level);
  },

  getEssentialTerms() {
    return this.terms.filter(t => t.level === 'essential');
  },

  getRandomTerms(count) {
    const shuffled = [...this.terms].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  },

  getStats() {
    const categories = {};
    const levels = {};
    this.terms.forEach(t => {
      categories[t.category] = (categories[t.category] || 0) + 1;
      levels[t.level] = (levels[t.level] || 0) + 1;
    });
    return { total: this.terms.length, categories, levels };
  }
};

if (typeof window !== 'undefined') {
  window.GlossaryData = GlossaryData;
}
