"""Generate TypeScript data file from parsed JSON."""
import json
from pathlib import Path

JSON_PATH = Path(__file__).resolve().parent / "experimental_lessons.json"
OUT_PATH = Path(__file__).resolve().parent.parent / "khawarizmi-frontend" / "src" / "lib" / "experimental-lessons-data.ts"

data = json.loads(JSON_PATH.read_text(encoding="utf-8"))

def js_val(v) -> str:
    """Convert Python value to JavaScript/TypeScript literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        return f"`{escaped}`"
    if isinstance(v, list):
        items = ", ".join(js_val(i) for i in v)
        return f"[{items}]"
    if isinstance(v, dict):
        pairs = ", ".join(f"{k}: {js_val(val)}" for k, val in v.items())
        return f"{{{pairs}}}"
    return f"`{v}`"

def lesson_to_ts(lesson: dict) -> str:
    slug = lesson["slug"]
    title = lesson["title"]
    breadcrumb = lesson["breadcrumb"]
    objectives = lesson["objectives"]
    phases = lesson["phases"]
    return f"""
  "{slug}": {{
    titleAr: {js_val(title)},
    breadcrumb: {js_val(breadcrumb)},
    objectives: {js_val(objectives)},
    phases: {js_val(phases)}
  }}"""

parts = [lesson_to_ts(d) for d in data]
all_slugs = [d["slug"] for d in data]

ts_code = f"""// Auto-generated by scripts/gen_lessons_ts.py
// Source: {len(data)} parsed SVT HTML lessons

export interface LessonBlock {{
  type: "problem" | "document" | "simulation" | "scientific_text" | "bac_tip" | "quiz" | "text";
  title?: string;
  texts?: string[];
  buttons?: string[];
  active?: boolean;
  question?: string;
  options?: string[];
  correct?: number;
}}

export interface LessonPhase {{
  step: string;
  blocks: LessonBlock[];
}}

export interface ExperimentalLesson {{
  titleAr: string;
  breadcrumb: string;
  objectives: string[];
  phases: LessonPhase[];
}}

export const EXPERIMENTAL_LESSONS: Record<string, ExperimentalLesson> = {{{"," .join(parts)}
}};

export const EXPERIMENTAL_SLUGS: string[] = {js_val(all_slugs)};

export function getExperimentalLesson(slug: string): ExperimentalLesson {{
  return EXPERIMENTAL_LESSONS[slug] || EXPERIMENTAL_LESSONS["{all_slugs[0]}"];
}}
"""

OUT_PATH.write_text(ts_code, encoding="utf-8")
print(f"Generated {OUT_PATH} ({len(data)} lessons)")
