# routes/__init__.py
# Registry centralisé de tous les routers API

from . import (
    annales,
    auth,
    avatar,
    bac_blanc_intelligent,
    badges,
    chat,
    chatbot,
    cours,
    diagnostic,
    dual_coding,
    evaluate,
    exercices,
    flashcards,
    gamification,
    health,
    lexique,
    methodology,
    methodology_flashcards,
    mindmap,
    mindmap_methodology,
    mystery_box,
    orientation,
    payment,
    phase1,
    phase2,
    phase3,
    phase4,
    phase5,
    phase6,
    programme,
    progress,
    session,
    tuteur,
    tutor,
    videos,
)

ALL_ROUTERS = [
    # ── Core ──
    health.router,
    auth.router,
    chat.router,
    chatbot.router,
    cours.router,
    exercices.router,
    flashcards.router,
    mindmap.router,
    evaluate.router,
    session.router,
    payment.router,
    programme.router,
    progress.router,
    orientation.router,
    lexique.router,
    tuteur.router,
    videos.router,
    annales.router,
    dual_coding.router,
    # ── Gamification ──
    gamification.router,
    mystery_box.router,
    avatar.router,
    # ── Phase 1-6 ──
    phase1.router,
    phase2.router,
    badges.router,
    phase3.router,
    phase4.router,
    phase5.router,
    phase6.router,
    # ── Methodology Intelligence ──
    bac_blanc_intelligent.router,
    diagnostic.router,
    methodology.router,
    methodology_flashcards.router,
    mindmap_methodology.router,
    tutor.router,
]
