# routes/__init__.py
# Registry centralisé de tous les routers API

from . import (
    action_verbs,
    admin_analytics,
    ai_chat,
    ai_evaluate,
    annales,
    aujourdhui,
    auth,
    avatar,
    bac_blanc,
    bac_blanc_intelligent,
    badges,
    chapitres,
    chatbot,
    chatbot_engagement,
    cities,
    cours,
    dashboard,
    diagnostic,
    document_analysis,
    document_analysis_v2,
    dual_coding,
    duels,
    exercices,
    flashcards,
    gamification,
    gems,
    health,
    leaderboard,
    lessons,
    lexique,
    manhadjiya,
    methodology,
    methodology_flashcards,
    mindmap,
    mindmap_methodology,
    mystery_box,
    onboarding,
    orientation,
    payment,
    phase1,
    phase3,
    phase5,
    phase6,
    programme,
    progress,
    pulse,
    session,
    social,
    streaks,
    tutor,
    videos,
)

ALL_ROUTERS = [
    # ── Core ──
    health.router,
    auth.router,
    chapitres.router,
    chatbot.router,
    cours.router,
    exercices.router,
    flashcards.router,
    mindmap.router,
    session.router,
    payment.router,
    programme.router,
    progress.router,
    dashboard.router,
    orientation.router,
    lexique.router,
    videos.router,
    annales.router,
    dual_coding.router,
    # ── Gamification ──
    gamification.router,
    mystery_box.router,
    avatar.router,
    # ── Phase 1-6 (phase2, phase4, badges retirés : doublons ou non utilisés) ──
    phase1.router,
    phase3.router,
    phase5.router,
    phase6.router,
    chatbot_engagement.router,
    # ── AI Orchestrator ──
    ai_chat.router,
    ai_evaluate.router,
    # ── Methodology Intelligence ──
    diagnostic.router,
    methodology.router,
    methodology_flashcards.router,
    mindmap_methodology.router,
    # ── Tutor & Bac Blanc ──
    tutor.router,
    bac_blanc_intelligent.router,
    # ── Social Hub (Messenger + Blog + Fichiers) ──
    social.router,
    # ── Admin Analytics (Dashboard Professeur) ──
    admin_analytics.router,
    # ── Document Analysis (v1 : scenarios/progress/weak-spots + v2 : evaluate) ──
    document_analysis.router,
    document_analysis_v2.router,
    # ── Action Verbs ──
    action_verbs.router,
    # ── Gamification Sprint 1 ──
    streaks.router,
    badges.router,
    # ── Gamification Sprint 2 ──
    gems.router,
    duels.router,
    leaderboard.router,
    # ── Gamification Sprint 3 ──
    cities.router,
    onboarding.router,
    # ── Manhadjiya (LOT8 — Base de connaissance scientifique) ──
    manhadjiya.router,
    # ── PULSE Dashboard ──
    pulse.router,
    # ── Aujourd'hui (accueil) · Leçons actives · Bac Blanc v1 (immersif) ──
    aujourdhui.router,
    lessons.router,
    bac_blanc.router,
]
